/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qkartlocal;
import org.apache.commons.io.FileUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;

import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

// import dev.failsafe.internal.util.Assert;

import java.time.Duration;
import io.github.bonigarcia.wdm.WebDriverManager;
import java.io.File;
import java.io.IOException;

import qkartlocal.pages.Register;
import qkartlocal.pages.Home;
import qkartlocal.pages.Login;

public class TestCases {

    ChromeDriver driver;
    WebDriverWait wait = new WebDriverWait(driver,Duration.ofSeconds(30));
    String lastGeneratedUserName=null;
    // String password=null;

    @BeforeTest
    public void startBrowser() {
            // System.setProperty("java.util.logging.config.file", "logging.properties");

            // NOT NEEDED FOR SELENIUM MANAGER
            // WebDriverManager.chromedriver().timeout(30).setup();

        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();

        // You can also use FirefoxDriver or other browsers similarly
        // WebDriverManager.firefoxdriver().setup();
        // WebDriver driver = new FirefoxDriver();

        // Example test
        driver.get("https://www.google.co.in/");
        driver.manage().window().maximize();
    }
    public void takeScreenshotfor() throws IOException{
        File SrcFile=((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
        //Move image file to new destination
        File DestFile=new File("srceenshot/outpu1.png");
        //Copy file at destination
        FileUtils.copyFile(SrcFile, DestFile);
    }

    @Test
    public void testCase01() throws InterruptedException{
        boolean status=false;
        Register register=new Register(driver);
        Login login=new Login(driver);
        register.navigateToRegisterPage();
        status=register.newRegister("harish", "Harish123", true);
        Assert.assertTrue(status,"registration failed");
        lastGeneratedUserName=register.lastGeneratedusr;
        login.navigateToLoginPage();
        status=login.newLogin(lastGeneratedUserName, "Harish123");
        Assert.assertTrue(status,"login failed");

    }

    @Test
    public void testCase02() throws InterruptedException{
        System.out.println("t01");
        boolean status=false;
        Register register=new Register(driver);
        Login login=new Login(driver);
        register.navigateToRegisterPage();
        status=register.newRegister("harish", "Harish123", true);
        Assert.assertTrue(status,"registration failed");
        lastGeneratedUserName=register.lastGeneratedusr;
        register.navigateToRegisterPage();
        status=register.newRegister(lastGeneratedUserName, "Harish123", false);
        Assert.assertFalse(status,"registration failed");
    }

    @Test
    public void testCase03() throws InterruptedException{
        System.out.println("t01");

        Home home=new Home(driver);
        home.navigateToHomePage();
        WebElement searchbar=driver.findElement(By.xpath("//input[@name='search']"));
        searchbar.clear();
        searchbar.sendKeys("yonex");
        Thread.sleep(3000);
       
        // wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//p[@class='MuiTypography-root MuiTypography-body1 css-yg30e6']")));
        WebElement headText=driver.findElement(By.xpath("//p[@class='MuiTypography-root MuiTypography-body1 css-yg30e6']"));
        // if(headText.getText().contains("YONEX")){

        // }
        Assert.assertTrue(headText.getText().contains("YONEX"));
        searchbar.clear();
        searchbar.sendKeys("jkdfsdjfsa");
        wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//h4[text()=' No products found ']")));

        // Thread.sleep(2000);
        WebElement noproduct=driver.findElement(By.xpath("//h4[text()=' No products found ']"));
        Assert.assertTrue(noproduct.getText().contains("No products found"));

    }

    @Test
    public void testCase04() throws InterruptedException{
        System.out.println("t01");

        Home home=new Home(driver);
        home.navigateToHomePage();
        WebElement searchBar=driver.findElement(By.xpath("//input[@name='search']"));
        searchBar.clear();
        searchBar.sendKeys("shoes");
        Thread.sleep(2000);
        WebElement sizeBar=driver.findElement(By.xpath("//button[text()='Size chart']"));
        sizeBar.click();
        WebElement sizeChart=driver.findElement(By.xpath("//div[@role='dialog']"));
        boolean status=sizeChart.isDisplayed();
        Assert.assertTrue(status,"size chart is not displayed");
    }
    

}
